// Generated by CoffeeScript 1.4.0
(function() {
  var hideQRCodePopup, showQRCodePopup;

  showQRCodePopup = function() {
    $('#mask').show();
    $('#qrcode_popup').show();
    return $('#card').hide();
  };

  hideQRCodePopup = function() {
    $('#mask').hide();
    $('#qrcode_popup').hide();
    return $('#card').show();
  };

  $('body').on('click', function() {
    return popupQR();
  });

  window.addEventListener('devicemotion', function(evt) {
    var z;
    z = evt.accelerationIncludingGravity.z;
    if (z > 3) {
      return showQRCodePopup();
    } else {
      return hideQRCodePopup();
    }
  });

}).call(this);
